import Layout from "../componets/Layout";
import Shop from "../componets/Shop";
import Home from "../componets/Home";
import Cart from "../componets/Cart";
import Wishlist from "../componets/Wishlist";
import About from "../componets/About";
import Contact from "../componets/Contact";
import Login from "../componets/Login";
import Signup from "../componets/Signup";
export { Layout, Home, Shop, Cart, About, Contact, Login, Signup, Wishlist };
